version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped

    environment:
      - MYSQL_ROOT_PASSWORD=M1!&bqP3
      - MYSQL_DATABASE=pod_urjc
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: aliciamm/gestionpod:latest
    restart: unless-stopped

    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_DATABASE=pod_urjc
      - MYSQL_USER=root
      - MYSQL_PASSWORD=M1!&bqP3
      - API_PORT=8080
      - APP_URL=https://app.gestionpod.aliciamm.xyz
      - SMTP_HOST=smtp-mail.outlook.com
      - SMTP_PASSWORD=H6Er4tWqpi2
      - SMTP_USER=gestionpod@outlook.com
      - SMTP_PORT=587
      - JWT_SECRET="%aWR&1Zmh=vaXkzO$DkyM==3VyZmhvc2l&=kaIm%"
    volumes:
      - .m2:/root/.m2

    stdin_open: true
    tty: true

volumes:
  db:

networks:
  default:
    external:
      name: proxied-containers
